name: Terraform Plan, Stage & Apply

on:
  workflow_call:
    inputs:
      terraform_dir:
        required: true
        type: string
      tfvars_file:
        required: true
        type: string
      run_apply:
        required: false
        type: boolean
        default: false

    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_TENANT_ID:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Terraform Init
        working-directory: ${{ inputs.terraform_dir }}
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: true

      - name: Terraform Plan
        working-directory: ${{ inputs.terraform_dir }}
        run: terraform plan -var-file="${{ inputs.tfvars_file }}"
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: true
          
  # manual-approval:
  #   runs-on: ubuntu-latest
  #   needs: plan
  #   environment: manual-approval   # ðŸ‘ˆ This triggers manual approval
  #   steps:
  #     - name: Awaiting manual approval
  #       run: echo "Approval granted. Proceeding with apply..."

  stage:
    name: Approval(Stage)
    if: ${{ github.ref == 'refs/heads/main' && inputs.run_apply }}
    needs: plan
    runs-on: ubuntu-latest
    environment:
      name: manual-approval    # ðŸ‘ˆ This triggers manual approval
    steps:
      - name: Wait for approval
        run: echo "Approval granted. Proceeding with apply..."

  apply:
    name: Terraform Apply
    if: ${{ github.ref == 'refs/heads/main' && inputs.run_apply }}
    needs: stage
    #needs: manual-approval
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Terraform Init
        working-directory: ${{ inputs.terraform_dir }}
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: true

      - name: Terraform Apply
        working-directory: ${{ inputs.terraform_dir }}
        run: terraform apply -auto-approve -var-file="${{ inputs.tfvars_file }}"
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: true
